# Generated by Django 3.2.25 on 2024-11-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20241105_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exercise',
            name='tips',
            field=models.TextField(default=''),
        ),
    ]
