# Generated by Django 3.2.25 on 2024-12-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20241129_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodypart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
