# Generated by Django 3.2.25 on 2024-11-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20241103_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='week_descriptions',
            field=models.JSONField(default=dict),
        ),
    ]
