# Generated by Django 3.2.25 on 2024-12-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_workout_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='image',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='price',
        ),
    ]
