# Generated by Django 3.2.25 on 2024-11-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_tracker_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
